2022-03-16 at 20:40:18|ERROR|django.views.decorators.csrf|wrapped_view|An error has been caught in function 'wrapped_view', process 'MainProcess' (2571), thread 'Thread-1' (123145564008448):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe5e15c8050>
    └ <Thread(Thread-1, started daemon 123145564008448)>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe5e15c7dd0>
    └ <Thread(Thread-1, started daemon 123145564008448)>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1, started daemon 123145564008448)>
    │    │        │    └ (<socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8000), raddr=('...
    │    │        └ <Thread(Thread-1, started daemon 123145564008448)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe5e74f9350>>
    └ <Thread(Thread-1, started daemon 123145564008448)>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 55455)
    │    │              └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8000), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe5e609bef0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe5e74f9350>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe5e74f9350>
    │    │                   │        └ ('127.0.0.1', 55455)
    │    │                   └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8000), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe5e74f9350>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe5e67fd680>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe5e75b34d0>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 176, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe5e67fd710>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe5e75b34d0>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 201, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe5e67eb0e0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe5e74f9350>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe5e75b34d0>
    │       └ <function BaseHandler.run at 0x7fe5e67f5dd0>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe5e7589e90>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe5e67fa170>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe5e7589e90>
    │    │        │           │    └ {'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public', '__CFBundleIdentifie...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe5e7589e90>
    │    │        └ <django.contrib.staticfiles.handlers.StaticFilesHandler object at 0x7fe5e7526490>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe5e7589e90>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
    return self.application(environ, start_response)
           │    │           │        └ <bound method BaseHandler.start_response of <django.core.servers.basehttp.ServerHandler object at 0x7fe5e7589e90>>
           │    │           └ {'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public', '__CFBundleIdentifie...
           │    └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe5e60adf50>
           └ <django.contrib.staticfiles.handlers.StaticFilesHandler object at 0x7fe5e7526490>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               │    └ <function BaseHandler.get_response at 0x7fe5e6789680>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe5e60adf50>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe5e759fdd0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe5e60adf50>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe5e759dad0>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe5e759f290>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe5e759dad0>
               └ None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe5e759da90>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe5e7584320>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe5e759da90>
               └ None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe5e74cf950>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe5e75987a0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe5e74cf950>
               └ None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe5e758ff10>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe5e7598830>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe5e758ff10>
               └ None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe5e758fe90>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe5e757b0e0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe5e758fe90>
               └ None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe5e75100d0>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe5e61167a0>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe5e75100d0>
               └ None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe5e7510ed0>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe5e6116f80>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe5e7510ed0>
               └ None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               └ <check_data.middleware.CheckRequest object at 0x7fe5e611d450>

  File "/Users/pink/Code/uis/check_data/middleware.py", line 15, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               │    └ <function BaseHandler._get_response at 0x7fe5e6116680>
               └ <check_data.middleware.CheckRequest object at 0x7fe5e611d450>

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               │            └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe5e60adf50>>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {}
               │                │         └ ()
               │                └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
               └ <function login_auth.<locals>.is_login at 0x7fe5e6a427a0>
> File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           │          │       └ {}
           │          └ (<WSGIRequest: POST '/api/v1/user/get_friend_list'>,)
           └ <function login_auth.<locals>.is_login at 0x7fe5e6a424d0>

  File "/Users/pink/Code/uis/user/utils/basic.py", line 159, in is_login
    result = func(res)
             │    └ <WSGIRequest: POST '/api/v1/user/get_friend_list'>
             └ <function get_friend_list at 0x7fe5e6a423b0>

  File "/Users/pink/Code/uis/user/views.py", line 319, in get_friend_list
    return JsonResponse({'code': 200, 'msg': 'security', 'data': result}, safe=False)
           │                                                     └ [{'uid': UUID('28f0595c-1e2c-4b0f-84f8-fdb29e263b0e'), 'account': '5201314', 'nick_name': '测试账号', 'avatar': 'http://127.0.0.1...
           └ <class 'django.http.response.JsonResponse'>

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
           │    │     │         │          └ {}
           │    │     │         └ <class 'django.core.serializers.json.DjangoJSONEncoder'>
           │    │     └ {'code': 200, 'msg': 'security', 'data': [{'uid': UUID('28f0595c-1e2c-4b0f-84f8-fdb29e263b0e'), 'account': '5201314', 'nick_n...
           │    └ <function dumps at 0x7fe5e3605f80>
           └ <module 'json' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py'>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
      │          └ {'code': 200, 'msg': 'security', 'data': [{'uid': UUID('28f0595c-1e2c-4b0f-84f8-fdb29e263b0e'), 'account': '5201314', 'nick_n...
      └ {}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
             │    │          └ {'code': 200, 'msg': 'security', 'data': [{'uid': UUID('28f0595c-1e2c-4b0f-84f8-fdb29e263b0e'), 'account': '5201314', 'nick_n...
             │    └ <function JSONEncoder.iterencode at 0x7fe5e360f320>
             └ <django.core.serializers.json.DjangoJSONEncoder object at 0x7fe5e7657e10>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
           │           └ {'code': 200, 'msg': 'security', 'data': [{'uid': UUID('28f0595c-1e2c-4b0f-84f8-fdb29e263b0e'), 'account': '5201314', 'nick_n...
           └ <_json.Encoder object at 0x7fe5e76c12f0>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
                           └ <Option: 男>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

TypeError: Object of type Option is not JSON serializable
